---
- name: install_geoserver_application | stop tomcat 
  shell: service tomcat8 stop
  become: yes

- name: install_geoserver_application | change catalina.properties
  command: sed -i -e 's/xom-\*\.jar/xom-\*\.jar,bcprov\*\.jar/g' /var/lib/tomcat8/conf/catalina.properties
  become: yes

- name: install_geonode_packages | write tomcat8
  template: 
    src: ./templates/gs/tomcat8 
    dest: /etc/default/tomcat8
  become: yes

- name: install_geoserver_application | stop apache2 
  shell: service apache2 stop
  become: yes

# folder setup
- name: install_geoserver_application | copy geoserver directory
  command: cp -Rf {{ project_path }}/downloaded/geoserver-2.14.x.war /var/lib/tomcat8/webapps/geoserver.war
  become: yes

# - name: install_geoserver_application | set permissions /var/lib/tomcat8/webapps/geoserver'
#   become: yes
#   file:
#     path: /var/lib/tomcat8/webapps/geoserver
#     owner: tomcat8
#     recurse: yes

- name: install_geoserver_application | create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: tomcat8
    mode: 0775
  become: yes
  with_items:
    - /data/geoserver-data
    - /data/geoserver-logs
    - /data/gwc_cache_dir

- name: install_geoserver_application | copy geoserver data directory
  become: yes
  command: cp -Rf {{ project_path }}/geoserver/data/. /data/geoserver-data/


# uncomment tomcat-admin first in install_geonode_packages.yml
# - name: install_geoserver_application | write tomcat-users.xml
#   template: 
#     src: ./templates/gs/tomcat-users.xml 
#     dest: /etc/tomcat8/tomcat-users.xml
#     owner: root
#     group: tomcat8
#   become: yes

- name: install_geoserver_application | write config.conf 
  template: 
    src: ./templates/gs/config.xml.j2 
    dest: /data/geoserver-data/security/filter/geonode-oauth2/config.xml
    owner: tomcat8
    group: tomcat8
  become: yes

- name: install_geoserver_application | write global.xml 
  template: 
    src: ./templates/gs/global.xml.j2 
    dest: /data/geoserver-data/global.xml
    owner: tomcat8
    group: tomcat8
  become: yes

- name: install_geoserver_application | write user.xml 
  template: 
    src: ./templates/gs/users.xml.j2
    dest: /data/geoserver-data/security/usergroup/default/users.xml
    owner: tomcat8
    group: tomcat8
  become: yes

- name: install_geoserver_application | start tomcat 
  shell: service tomcat8 start
  environment:
    JAVA_HOME=: /usr/
  become: yes
