---

- name: install_geonode_packages | install java 8
  become: yes
  apt: name={{item}} state=latest
  loop: ['openjdk-8-jdk-headless', 'default-jdk-headless']

- name: change default-java to openjdk8
  become: yes
  shell: update-java-alternatives --set /usr/lib/jvm/java-1.8.0-openjdk-amd64

- name: install_geonode_packages | install list of dependency packages
  become: yes
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - apache2
      - build-essential
      - default-jdk
      - gcc
      - gdal-bin
      - gettext
      - git
      - git-core
      - libapache2-mod-wsgi
      - libgdal-dev
      - libgdal20
      - libgeos-dev
      - libjpeg-dev
      - libpng-dev
      - libpq-dev
      - libproj-dev
      - libxml2
      - libxml2-dev
      - libxslt-dev
      - libxslt1-dev
      - nano
      - openssh-server
      - patch
      - postfix
      - postgis
      - postgresql
      - postgresql-10-postgis-2.4-scripts
      - postgresql-contrib
      - python-dev
      - python-gdal
      - python-pastescript
      - python-pil
      - python-pip
      - python-psycopg2
      - python-pycurl
      - python-urlgrabber
      - python-virtualenv
      - software-properties-common
      - tomcat8
      - unzip
      - vim
      - zip
      - zlib1g-dev

- name: install_geonode_packages | upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    autoremove: yes
    autoclean: yes
    purge: yes